CREATE TABLE urls (
	id SERIAL PRIMARY KEY NOT NULL, 
	url VARCHAR(400) NOT NULL UNIQUE, 
	shorturl VARCHAR(10) NOT NULL UNIQUE, 
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	clicked INTEGER NOT NULL,
	CHECK(clicked >=0)
);

CREATE OR REPLACE FUNCTION lyhennaUrl()
	RETURNS trigger AS
	$urlshortener$
		BEGIN
		INSERT INTO urls(shorturl)
		VALUES (CONCAT(MID(NEW.url,4)),NEW.id);
		RETURN NEW;
		END;
	$urlshortener$
LANGUAGE plpgsql;

CREATE TRIGGER shortFullUrl 
	AFTER INSERT 
	ON urls
	FOR EACH ROW 
	EXECUTE PROCEDURE lyhennaUrl(); 

CREATE SEQUENCE max_link_amount
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 10000
	CACHE 1
	CYCLE
	OWNED BY urls.url;
